platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!

target 'WhiteLabel_Example' do
  pod 'WhiteLabel', :path => '../'

  target 'WhiteLabel_Tests' do
    inherit! :search_paths
    
  end
end